### ISSUE TITLE
Is it possible to theme the playlist UI?

### ISSUE THREAD

**Issue by FontPeer** [leifniem/Black-VLC-Mac#1]
Player screen looks great, just curious if anything can be done about the ui background.
<img width="847" alt="screen" src="https://user-images.githubusercontent.com/28957080/28903491-3e026a12-77d3-11e7-9206-b48edaca1a51.png">

**Comment by leifniem** [comment]
At least Not in the Images Files as it seems. Haven't dug deeper tbh.

Am 3. Aug. 2017, 04:38 +0200 schrieb FontPeer <notifications@github.com>:
